import type { Carrier } from "@/lib/types/carrier"

export const MOCK_CARRIERS: Carrier[] = [
  {
    id: "carrier_polaraero",
    name: "Polar Aero Med",
    modes: ["air"],
    tempCapabilities: ["ultra_cold", "frozen", "refrigerated"],
    reliabilityScore: 96,
    coverageRegions: ["Global air routes"],
    totalCapacity: 24,
    availableCapacity: 8,
    contactEmail: "dispatch@polaraero.com",
    headquarters: "Zurich, Switzerland",
  },
  {
    id: "carrier_arctic_express",
    name: "Arctic Express Logistics",
    modes: ["air", "road"],
    tempCapabilities: ["ultra_cold", "frozen", "refrigerated"],
    reliabilityScore: 94,
    coverageRegions: ["Europe", "North America", "Middle East"],
    totalCapacity: 48,
    availableCapacity: 22,
    contactEmail: "ops@arctic-express.com",
    headquarters: "Amsterdam, Netherlands",
  },
  {
    id: "carrier_meditrans",
    name: "MediTrans Asia",
    modes: ["air", "road"],
    tempCapabilities: ["refrigerated"],
    reliabilityScore: 89,
    coverageRegions: ["Asia Pacific", "South Asia"],
    totalCapacity: 60,
    availableCapacity: 31,
    contactEmail: "ops@meditrans.asia",
    headquarters: "Mumbai, India",
  },
  {
    id: "carrier_pharmafreight",
    name: "PharmaFreight Global",
    modes: ["sea", "air"],
    tempCapabilities: ["frozen", "refrigerated"],
    reliabilityScore: 91,
    coverageRegions: ["Asia Pacific", "Europe", "Americas"],
    totalCapacity: 120,
    availableCapacity: 45,
    contactEmail: "logistics@pharmafreight.com",
    headquarters: "Singapore",
  },
]
