import type { CrewMember } from "@/lib/types/crew"

export const MOCK_CREWS: CrewMember[] = [
  {
    id: "crew_001",
    name: "Ravi Patel",
    email: "driver@arcticops.io",
    phone: "+91 98200 11234",
    transportMode: "road",
    licenseNumber: "MH-14-20190045",
    baseLocation: "Mumbai, India",
    performanceScore: 92,
    onTimePercent: 94,
    tempMaintenanceRecord: 98,
    incidentCount: 0,
    status: "on_duty",
    currentAssignmentId: "SH-2965",
    documents: [
      { id: "d_rp1", type: "driver_license", displayName: "Commercial Driver's License", status: "verified", expiryDate: "2027-06-30", issuingAuthority: "Maharashtra RTO" },
      { id: "d_rp2", type: "vehicle_fitness", displayName: "Vehicle Fitness Certificate", status: "verified", expiryDate: "2026-08-15", issuingAuthority: "NHAI" },
      { id: "d_rp3", type: "adr_cert", displayName: "ADR Certificate", status: "verified", expiryDate: "2027-12-31", issuingAuthority: "Cert Body India" },
      { id: "d_rp4", type: "medical", displayName: "Medical Fitness Certificate", status: "verified", expiryDate: "2026-09-15", issuingAuthority: "Apollo Hospitals" },
    ],
  },
  {
    id: "crew_003",
    name: "James Okafor",
    email: "j.okafor@arcticops.io",
    phone: "+234 802 111 9988",
    transportMode: "air",
    licenseNumber: "ATPL-NG-20150078",
    baseLocation: "Lagos, Nigeria",
    performanceScore: 95,
    onTimePercent: 97,
    tempMaintenanceRecord: 99,
    incidentCount: 0,
    status: "on_duty",
    currentAssignmentId: "SH-2847",
    documents: [
      { id: "d_jo1", type: "atpl", displayName: "ATPL License", status: "verified", expiryDate: "2027-09-15" },
      { id: "d_jo2", type: "medical_class1", displayName: "Class 1 Medical Certificate", status: "verified", expiryDate: "2026-03-01" },
      { id: "d_jo3", type: "type_rating", displayName: "B737 Type Rating", status: "verified", expiryDate: "2026-06-30" },
      { id: "d_jo4", type: "dangerous_goods", displayName: "Dangerous Goods by Air (CAT 6)", status: "verified", expiryDate: "2026-08-20" },
    ],
  },
  {
    id: "crew_005",
    name: "Kenji Nakamura",
    email: "k.nakamura@arcticops.io",
    phone: "+81 90 2234 5678",
    transportMode: "sea",
    licenseNumber: "JPN-STCW-20120044",
    baseLocation: "Yokohama, Japan",
    performanceScore: 93,
    onTimePercent: 95,
    tempMaintenanceRecord: 97,
    incidentCount: 0,
    status: "available",
    documents: [
      { id: "d_kn1", type: "stcw_cert", displayName: "STCW Certificate", status: "verified", expiryDate: "2027-11-30" },
      { id: "d_kn2", type: "medical_seafarer", displayName: "Seafarer Medical Certificate", status: "verified", expiryDate: "2026-05-15" },
      { id: "d_kn3", type: "imdg_cert", displayName: "IMDG Code Training Certificate", status: "verified", expiryDate: "2026-09-01" },
      { id: "d_kn4", type: "master_license", displayName: "Chief Officer License", status: "verified", expiryDate: "2028-03-20" },
    ],
  },
  {
    id: "crew_006",
    name: "Fatima Al-Rashidi",
    email: "f.alrashidi@arcticops.io",
    phone: "+971 50 345 6789",
    transportMode: "air",
    licenseNumber: "UAE-ATPL-20180092",
    baseLocation: "Dubai, UAE",
    performanceScore: 91,
    onTimePercent: 93,
    tempMaintenanceRecord: 98,
    incidentCount: 0,
    status: "on_duty",
    currentAssignmentId: "SH-1204",
    documents: [
      { id: "d_fa1", type: "atpl", displayName: "ATPL License", status: "verified", expiryDate: "2028-01-15" },
      { id: "d_fa2", type: "medical_class1", displayName: "Class 1 Medical Certificate", status: "verified", expiryDate: "2026-07-01" },
      { id: "d_fa3", type: "type_rating", displayName: "A320 Type Rating", status: "verified", expiryDate: "2026-04-30" },
    ],
  },
  {
    id: "crew_009",
    name: "Sophia Martins",
    email: "s.martins@arcticops.io",
    phone: "+55 11 99876 5432",
    transportMode: "air",
    licenseNumber: "BR-ATPL-20190055",
    baseLocation: "São Paulo, Brazil",
    performanceScore: 90,
    onTimePercent: 92,
    tempMaintenanceRecord: 97,
    incidentCount: 0,
    status: "available",
    documents: [
      { id: "d_sm1", type: "atpl", displayName: "ATPL License", status: "verified", expiryDate: "2027-05-20" },
      { id: "d_sm2", type: "medical_class1", displayName: "Class 1 Medical Certificate", status: "verified", expiryDate: "2026-02-15" },
      { id: "d_sm3", type: "type_rating", displayName: "B777 Type Rating", status: "verified", expiryDate: "2026-11-30" },
      { id: "d_sm4", type: "dangerous_goods", displayName: "Dangerous Goods by Air", status: "verified", expiryDate: "2026-09-01" },
    ],
  },
]
