import type { CrewMember } from "@/lib/types/crew"

export const MOCK_CREWS: CrewMember[] = [
  {
    id: "crew_001",
    name: "Ravi Patel",
    email: "driver@arcticops.io",
    phone: "+91 98200 11234",
    transportMode: "road",
    licenseNumber: "MH-14-20190045",
    baseLocation: "Mumbai, India",
    performanceScore: 92,
    onTimePercent: 94,
    tempMaintenanceRecord: 98,
    incidentCount: 0,
    status: "on_duty",
    currentAssignmentId: "ship_001",
    documents: [
      { id: "d_rp1", type: "driver_license", displayName: "Commercial Driver's License", status: "verified", expiryDate: "2027-06-30", issuingAuthority: "Maharashtra RTO" },
      { id: "d_rp2", type: "vehicle_fitness", displayName: "Vehicle Fitness Certificate", status: "verified", expiryDate: "2026-08-15", issuingAuthority: "NHAI" },
      { id: "d_rp3", type: "adr_cert", displayName: "ADR Certificate", status: "verified", expiryDate: "2025-12-31", issuingAuthority: "Cert Body India" },
      { id: "d_rp4", type: "medical", displayName: "Medical Fitness Certificate", status: "verified", expiryDate: "2026-03-15", issuingAuthority: "Apollo Hospitals" },
    ],
  },
  {
    id: "crew_002",
    name: "Elena Vasquez",
    email: "e.vasquez@arcticops.io",
    phone: "+34 612 345 678",
    transportMode: "road",
    licenseNumber: "ES-B-20180392",
    baseLocation: "Madrid, Spain",
    performanceScore: 88,
    onTimePercent: 91,
    tempMaintenanceRecord: 96,
    incidentCount: 1,
    status: "available",
    documents: [
      { id: "d_ev1", type: "driver_license", displayName: "European Driver's License (Cat C+E)", status: "verified", expiryDate: "2028-04-10" },
      { id: "d_ev2", type: "adr_cert", displayName: "ADR Certificate", status: "pending", expiryDate: "2026-01-20" },
      { id: "d_ev3", type: "medical", displayName: "Medical Fitness", status: "verified", expiryDate: "2025-11-01" },
    ],
  },
  {
    id: "crew_003",
    name: "James Okafor",
    email: "j.okafor@arcticops.io",
    phone: "+234 802 111 9988",
    transportMode: "air",
    licenseNumber: "ATPL-NG-20150078",
    baseLocation: "Lagos, Nigeria",
    performanceScore: 95,
    onTimePercent: 97,
    tempMaintenanceRecord: 99,
    incidentCount: 0,
    status: "on_duty",
    currentAssignmentId: "ship_003",
    documents: [
      { id: "d_jo1", type: "atpl", displayName: "ATPL License", status: "verified", expiryDate: "2027-09-15" },
      { id: "d_jo2", type: "medical_class1", displayName: "Class 1 Medical Certificate", status: "verified", expiryDate: "2026-03-01" },
      { id: "d_jo3", type: "type_rating", displayName: "B737 Type Rating", status: "verified", expiryDate: "2026-06-30" },
      { id: "d_jo4", type: "dangerous_goods", displayName: "Dangerous Goods by Air (CAT 6)", status: "verified", expiryDate: "2026-08-20" },
    ],
  },
  {
    id: "crew_004",
    name: "Hana Petrov",
    email: "h.petrov@arcticops.io",
    phone: "+420 776 321 456",
    transportMode: "road",
    licenseNumber: "CZ-C-20200156",
    baseLocation: "Prague, Czech Republic",
    performanceScore: 87,
    onTimePercent: 89,
    tempMaintenanceRecord: 95,
    incidentCount: 0,
    status: "available",
    documents: [
      { id: "d_hp1", type: "driver_license", displayName: "EU Driver's License (Cat C)", status: "verified", expiryDate: "2029-02-28" },
      { id: "d_hp2", type: "adr_cert", displayName: "ADR Certificate", status: "verified", expiryDate: "2025-10-15" },
      { id: "d_hp3", type: "transport_insurance", displayName: "CMR Insurance", status: "verified", expiryDate: "2026-12-31" },
    ],
  },
  {
    id: "crew_005",
    name: "Kenji Nakamura",
    email: "k.nakamura@arcticops.io",
    phone: "+81 90 2234 5678",
    transportMode: "sea",
    licenseNumber: "JPN-STCW-20120044",
    baseLocation: "Yokohama, Japan",
    performanceScore: 93,
    onTimePercent: 95,
    tempMaintenanceRecord: 97,
    incidentCount: 0,
    status: "on_duty",
    currentAssignmentId: "ship_006",
    documents: [
      { id: "d_kn1", type: "stcw_cert", displayName: "STCW Certificate", status: "verified", expiryDate: "2027-11-30" },
      { id: "d_kn2", type: "medical_seafarer", displayName: "Seafarer Medical Certificate", status: "verified", expiryDate: "2026-05-15" },
      { id: "d_kn3", type: "imdg_cert", displayName: "IMDG Code Training Certificate", status: "verified", expiryDate: "2026-09-01" },
      { id: "d_kn4", type: "master_license", displayName: "Chief Officer License", status: "verified", expiryDate: "2028-03-20" },
    ],
  },
  {
    id: "crew_006",
    name: "Fatima Al-Rashidi",
    email: "f.alrashidi@arcticops.io",
    phone: "+971 50 345 6789",
    transportMode: "air",
    licenseNumber: "UAE-ATPL-20180092",
    baseLocation: "Dubai, UAE",
    performanceScore: 91,
    onTimePercent: 93,
    tempMaintenanceRecord: 98,
    incidentCount: 0,
    status: "available",
    documents: [
      { id: "d_fa1", type: "atpl", displayName: "ATPL License", status: "verified", expiryDate: "2028-01-15" },
      { id: "d_fa2", type: "medical_class1", displayName: "Class 1 Medical Certificate", status: "verified", expiryDate: "2026-07-01" },
      { id: "d_fa3", type: "type_rating", displayName: "A320 Type Rating", status: "verified", expiryDate: "2026-04-30" },
    ],
  },
  {
    id: "crew_007",
    name: "Bruno Schmidt",
    email: "b.schmidt@arcticops.io",
    phone: "+49 176 8765 4321",
    transportMode: "rail",
    licenseNumber: "DE-RAIL-20160233",
    baseLocation: "Frankfurt, Germany",
    performanceScore: 85,
    onTimePercent: 88,
    tempMaintenanceRecord: 94,
    incidentCount: 1,
    status: "on_duty",
    currentAssignmentId: "ship_009",
    documents: [
      { id: "d_bs1", type: "rail_license", displayName: "Railway Vehicle Driver License", status: "verified", expiryDate: "2027-07-31" },
      { id: "d_bs2", type: "dangerous_goods_rail", displayName: "RID Dangerous Goods Certificate", status: "expired", expiryDate: "2025-09-30" },
      { id: "d_bs3", type: "medical_rail", displayName: "Rail Operator Medical Cert.", status: "verified", expiryDate: "2026-10-15" },
    ],
  },
  {
    id: "crew_008",
    name: "Amara Diallo",
    email: "a.diallo@arcticops.io",
    phone: "+221 77 456 7890",
    transportMode: "road",
    licenseNumber: "SN-B-20210087",
    baseLocation: "Dakar, Senegal",
    performanceScore: 84,
    onTimePercent: 86,
    tempMaintenanceRecord: 92,
    incidentCount: 2,
    status: "off_duty",
    documents: [
      { id: "d_ad1", type: "driver_license", displayName: "Professional Driver's License", status: "verified", expiryDate: "2028-11-30" },
      { id: "d_ad2", type: "adr_cert", displayName: "ADR Certificate", status: "pending", expiryDate: "2026-02-28" },
    ],
  },
  {
    id: "crew_009",
    name: "Sophia Martins",
    email: "s.martins@arcticops.io",
    phone: "+55 11 99876 5432",
    transportMode: "air",
    licenseNumber: "BR-ATPL-20190055",
    baseLocation: "São Paulo, Brazil",
    performanceScore: 90,
    onTimePercent: 92,
    tempMaintenanceRecord: 97,
    incidentCount: 0,
    status: "available",
    documents: [
      { id: "d_sm1", type: "atpl", displayName: "ATPL License", status: "verified", expiryDate: "2027-05-20" },
      { id: "d_sm2", type: "medical_class1", displayName: "Class 1 Medical Certificate", status: "verified", expiryDate: "2026-02-15" },
      { id: "d_sm3", type: "type_rating", displayName: "B777 Type Rating", status: "verified", expiryDate: "2026-11-30" },
      { id: "d_sm4", type: "dangerous_goods", displayName: "Dangerous Goods by Air", status: "verified", expiryDate: "2026-09-01" },
    ],
  },
  {
    id: "crew_010",
    name: "Lars Eriksson",
    email: "l.eriksson@arcticops.io",
    phone: "+46 70 234 5678",
    transportMode: "sea",
    licenseNumber: "SE-STCW-20140078",
    baseLocation: "Gothenburg, Sweden",
    performanceScore: 89,
    onTimePercent: 91,
    tempMaintenanceRecord: 96,
    incidentCount: 0,
    status: "available",
    documents: [
      { id: "d_le1", type: "stcw_cert", displayName: "STCW Certificate", status: "verified", expiryDate: "2028-06-30" },
      { id: "d_le2", type: "medical_seafarer", displayName: "Seafarer Medical Certificate", status: "verified", expiryDate: "2026-01-10" },
      { id: "d_le3", type: "imdg_cert", displayName: "IMDG Code Certificate", status: "verified", expiryDate: "2027-02-28" },
    ],
  },
  {
    id: "crew_011",
    name: "Min-jun Lee",
    email: "m.lee@arcticops.io",
    phone: "+82 10 5678 9012",
    transportMode: "road",
    licenseNumber: "KR-1-20220134",
    baseLocation: "Seoul, South Korea",
    performanceScore: 91,
    onTimePercent: 94,
    tempMaintenanceRecord: 99,
    incidentCount: 0,
    status: "available",
    documents: [
      { id: "d_ml1", type: "driver_license", displayName: "Type 1 Driver License", status: "verified", expiryDate: "2030-08-20" },
      { id: "d_ml2", type: "adr_cert", displayName: "Hazmat Transport Certification", status: "verified", expiryDate: "2026-05-31" },
      { id: "d_ml3", type: "medical", displayName: "Medical Fitness Certificate", status: "verified", expiryDate: "2027-01-15" },
    ],
  },
  {
    id: "crew_012",
    name: "Nadia Kowalski",
    email: "n.kowalski@arcticops.io",
    phone: "+48 501 234 567",
    transportMode: "rail",
    licenseNumber: "PL-RAIL-20170188",
    baseLocation: "Warsaw, Poland",
    performanceScore: 86,
    onTimePercent: 88,
    tempMaintenanceRecord: 93,
    incidentCount: 0,
    status: "off_duty",
    documents: [
      { id: "d_nk1", type: "rail_license", displayName: "Railway Driver License", status: "verified", expiryDate: "2026-12-31" },
      { id: "d_nk2", type: "dangerous_goods_rail", displayName: "RID Certificate", status: "verified", expiryDate: "2026-08-30" },
      { id: "d_nk3", type: "medical_rail", displayName: "Rail Medical Certificate", status: "verified", expiryDate: "2026-06-01" },
    ],
  },
  {
    id: "crew_013",
    name: "Olumide Adeyemi",
    email: "o.adeyemi@arcticops.io",
    phone: "+234 803 456 7890",
    transportMode: "air",
    licenseNumber: "NG-CPL-20200066",
    baseLocation: "Abuja, Nigeria",
    performanceScore: 83,
    onTimePercent: 85,
    tempMaintenanceRecord: 91,
    incidentCount: 1,
    status: "available",
    documents: [
      { id: "d_oa1", type: "cpl", displayName: "CPL License", status: "verified", expiryDate: "2026-10-20" },
      { id: "d_oa2", type: "medical_class1", displayName: "Class 1 Medical", status: "verified", expiryDate: "2026-04-01" },
      { id: "d_oa3", type: "dangerous_goods", displayName: "Dangerous Goods Certificate", status: "pending", expiryDate: "2026-01-15" },
    ],
  },
  {
    id: "crew_014",
    name: "Priya Sundaram",
    email: "p.sundaram@arcticops.io",
    phone: "+91 98123 45678",
    transportMode: "sea",
    licenseNumber: "IN-STCW-20180099",
    baseLocation: "Chennai, India",
    performanceScore: 88,
    onTimePercent: 90,
    tempMaintenanceRecord: 95,
    incidentCount: 0,
    status: "available",
    documents: [
      { id: "d_ps1", type: "stcw_cert", displayName: "STCW Certificate", status: "verified", expiryDate: "2027-09-30" },
      { id: "d_ps2", type: "medical_seafarer", displayName: "Seafarer Medical Certificate", status: "verified", expiryDate: "2026-08-15" },
      { id: "d_ps3", type: "imdg_cert", displayName: "IMDG Code Certificate", status: "verified", expiryDate: "2027-04-30" },
    ],
  },
  {
    id: "crew_015",
    name: "Aleksei Volkov",
    email: "a.volkov@arcticops.io",
    phone: "+7 916 234 5678",
    transportMode: "rail",
    licenseNumber: "RU-RAIL-20140211",
    baseLocation: "Moscow, Russia",
    performanceScore: 82,
    onTimePercent: 84,
    tempMaintenanceRecord: 90,
    incidentCount: 2,
    status: "off_duty",
    documents: [
      { id: "d_av1", type: "rail_license", displayName: "Locomotive Driver Certificate", status: "verified", expiryDate: "2026-05-31" },
      { id: "d_av2", type: "dangerous_goods_rail", displayName: "GOST Hazmat Rail Certificate", status: "verified", expiryDate: "2025-12-20" },
      { id: "d_av3", type: "medical_rail", displayName: "Medical Fitness Rail", status: "pending", expiryDate: "2026-03-10" },
    ],
  },
]
