import type { ComplianceDocument } from "@/lib/types/compliance"

export const MOCK_DOCUMENTS: ComplianceDocument[] = [
  // ── SH-2847 · PharmaAlpha · Insulin Glargine · Mumbai → Frankfurt ──────────
  { id: "doc_001", shipmentId: "SH-2847", tenantId: "tenant_pharma_alpha", type: "certificate_of_analysis",  displayName: "Certificate of Analysis — Insulin Glargine Batch IG-2847",      status: "complete",  uploadedAt: "2026-03-05T16:00:00Z", expiresAt: "2027-03-05T16:00:00Z", uploadedBy: "Alex Morgan",   fileSize: "1.2 MB" },
  { id: "doc_002", shipmentId: "SH-2847", tenantId: "tenant_pharma_alpha", type: "air_waybill",              displayName: "Air Waybill — Polar Aero Med AWB-2847",                        status: "complete",  uploadedAt: "2026-03-07T07:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "420 KB" },
  { id: "doc_010", shipmentId: "SH-2847", tenantId: "tenant_pharma_alpha", type: "packing_declaration",      displayName: "Packing List & Declaration — IG-2847",                         status: "complete",  uploadedAt: "2026-03-05T18:00:00Z",                                    uploadedBy: "Dr. Sarah Chen",fileSize: "310 KB" },
  { id: "doc_011", shipmentId: "SH-2847", tenantId: "tenant_pharma_alpha", type: "gdp_compliance",           displayName: "GDP Compliance Certificate — Polar Aero Med",                  status: "complete",  uploadedAt: "2026-03-06T09:00:00Z", expiresAt: "2026-12-31T00:00:00Z", uploadedBy: "Alex Morgan",   fileSize: "890 KB" },
  { id: "doc_012", shipmentId: "SH-2847", tenantId: "tenant_pharma_alpha", type: "temperature_log",          displayName: "Pre-Shipment Temperature Log — Mumbai WH, 72 h",               status: "complete",  uploadedAt: "2026-03-07T06:30:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "2.1 MB" },
  { id: "doc_013", shipmentId: "SH-2847", tenantId: "tenant_pharma_alpha", type: "invoice",                  displayName: "Commercial Invoice — PharmaAlpha × ArcticOps #INV-2847",      status: "complete",  uploadedAt: "2026-03-05T15:00:00Z",                                    uploadedBy: "Dr. Sarah Chen",fileSize: "205 KB" },
  { id: "doc_014", shipmentId: "SH-2847", tenantId: "tenant_pharma_alpha", type: "customs_declaration",      displayName: "EU Import Customs Declaration — Frankfurt FRA",                 status: "complete",  uploadedAt: "2026-03-07T08:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "560 KB" },
  { id: "doc_015", shipmentId: "SH-2847", tenantId: "tenant_pharma_alpha", type: "health_certificate",       displayName: "EU Health Certificate — EMA Batch Release IG-2847",           status: "pending",                                                                          uploadedBy: "Dr. Sarah Chen" },
  { id: "doc_016", shipmentId: "SH-2847", tenantId: "tenant_pharma_alpha", type: "export_permit",            displayName: "India CDSCO Export Permit — Insulin Glargine",                 status: "complete",  uploadedAt: "2026-03-04T14:00:00Z", expiresAt: "2026-09-04T00:00:00Z", uploadedBy: "Alex Morgan",   fileSize: "340 KB" },
  { id: "doc_017", shipmentId: "SH-2847", tenantId: "tenant_pharma_alpha", type: "dangerous_goods",          displayName: "IATA Dangerous Goods Declaration — Dry Ice DG-2847",           status: "missing" },

  // ── SH-1204 · BioVerde · BCG Vaccines · Brussels → Nairobi ─────────────────
  { id: "doc_003", shipmentId: "SH-1204", tenantId: "tenant_bioverde",     type: "certificate_of_analysis",  displayName: "Certificate of Analysis — BCG Vaccine Batch BCV-1204",        status: "complete",  uploadedAt: "2026-03-04T12:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "1.4 MB" },
  { id: "doc_004", shipmentId: "SH-1204", tenantId: "tenant_bioverde",     type: "import_permit",            displayName: "Kenya Import Permit — Ministry of Health",                     status: "pending",                                                                          uploadedBy: "Dr. Sarah Chen" },
  { id: "doc_018", shipmentId: "SH-1204", tenantId: "tenant_bioverde",     type: "bill_of_lading",           displayName: "Sea Bill of Lading — Maersk BL-1204",                         status: "complete",  uploadedAt: "2026-03-03T09:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "480 KB" },
  { id: "doc_019", shipmentId: "SH-1204", tenantId: "tenant_bioverde",     type: "gdp_compliance",           displayName: "GDP Compliance — Maersk Cold Chain Cert",                     status: "complete",  uploadedAt: "2026-03-03T10:00:00Z", expiresAt: "2026-12-31T00:00:00Z", uploadedBy: "Alex Morgan",   fileSize: "720 KB" },
  { id: "doc_020", shipmentId: "SH-1204", tenantId: "tenant_bioverde",     type: "temperature_log",          displayName: "In-Transit Temperature Log — Nairobi Port to Hub",            status: "complete",  uploadedAt: "2026-03-06T14:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "3.3 MB" },
  { id: "doc_021", shipmentId: "SH-1204", tenantId: "tenant_bioverde",     type: "phytosanitary",            displayName: "WHO Phytosanitary / Immunisation Certificate — BCV-1204",     status: "missing" },
  { id: "doc_022", shipmentId: "SH-1204", tenantId: "tenant_bioverde",     type: "invoice",                  displayName: "Commercial Invoice — BioVerde × ArcticOps #INV-1204",         status: "complete",  uploadedAt: "2026-03-03T11:00:00Z",                                    uploadedBy: "Dr. Sarah Chen",fileSize: "195 KB" },

  // ── SH-3091 · CryoMed · mRNA Vaccines · Zürich → Toronto ───────────────────
  { id: "doc_005", shipmentId: "SH-3091", tenantId: "tenant_cryomed",      type: "certificate_of_analysis",  displayName: "Certificate of Analysis — mRNA-1273 Batch MR-3091",           status: "complete",  uploadedAt: "2026-03-06T10:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "1.8 MB" },
  { id: "doc_023", shipmentId: "SH-3091", tenantId: "tenant_cryomed",      type: "air_waybill",              displayName: "Air Waybill — Swiss WorldCargo AWB-3091",                     status: "complete",  uploadedAt: "2026-03-07T11:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "390 KB" },
  { id: "doc_024", shipmentId: "SH-3091", tenantId: "tenant_cryomed",      type: "import_permit",            displayName: "Canada Health Import Permit — mRNA-1273",                     status: "complete",  uploadedAt: "2026-03-05T16:00:00Z", expiresAt: "2026-06-05T00:00:00Z", uploadedBy: "Alex Morgan",   fileSize: "520 KB" },
  { id: "doc_025", shipmentId: "SH-3091", tenantId: "tenant_cryomed",      type: "dangerous_goods",          displayName: "IATA DG Declaration — LN₂ Vapour Shipper DG-3091",           status: "complete",  uploadedAt: "2026-03-07T10:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "670 KB" },
  { id: "doc_026", shipmentId: "SH-3091", tenantId: "tenant_cryomed",      type: "gdp_compliance",           displayName: "Swiss Medic GDP Certificate — Swiss WorldCargo",              status: "complete",  uploadedAt: "2026-03-06T12:00:00Z", expiresAt: "2026-12-31T00:00:00Z", uploadedBy: "Alex Morgan",   fileSize: "810 KB" },
  { id: "doc_027", shipmentId: "SH-3091", tenantId: "tenant_cryomed",      type: "temperature_log",          displayName: "Cold-Chain Logger Export — ZRH → YYZ (Full Route)",           status: "pending",                                                                          uploadedBy: "Alex Morgan" },

  // ── SH-3110 · CryoMed · Cord Blood Cells · London → Sydney ─────────────────
  { id: "doc_006", shipmentId: "SH-3110", tenantId: "tenant_cryomed",      type: "certificate_of_analysis",  displayName: "Certificate of Analysis — Cord Blood Batch CB-3110",          status: "complete",  uploadedAt: "2026-03-06T11:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "1.6 MB" },
  { id: "doc_008", shipmentId: "SH-3110", tenantId: "tenant_cryomed",      type: "import_permit",            displayName: "Australian Quarantine Import Permit — DAFF",                  status: "missing" },
  { id: "doc_028", shipmentId: "SH-3110", tenantId: "tenant_cryomed",      type: "air_waybill",              displayName: "Air Waybill — Qantas Freight AWB-3110",                       status: "complete",  uploadedAt: "2026-03-07T15:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "410 KB" },
  { id: "doc_029", shipmentId: "SH-3110", tenantId: "tenant_cryomed",      type: "health_certificate",       displayName: "TGA Health Certificate — Cord Blood CB-3110",                 status: "pending",                                                                          uploadedBy: "Dr. Sarah Chen" },
  { id: "doc_030", shipmentId: "SH-3110", tenantId: "tenant_cryomed",      type: "dangerous_goods",          displayName: "IATA DG Declaration — Cryogenic Liquid DG-3110",             status: "complete",  uploadedAt: "2026-03-07T14:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "690 KB" },
  { id: "doc_031", shipmentId: "SH-3110", tenantId: "tenant_cryomed",      type: "packing_declaration",      displayName: "Dry Shipper Packing Declaration — CB-3110",                   status: "complete",  uploadedAt: "2026-03-06T13:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "280 KB" },

  // ── SH-2965 · CryoMed · Tacrolimus · Seoul → New Delhi ─────────────────────
  { id: "doc_007", shipmentId: "SH-2965", tenantId: "tenant_cryomed",      type: "certificate_of_analysis",  displayName: "Certificate of Analysis — Tacrolimus Batch TC-2965",          status: "complete",  uploadedAt: "2026-03-06T16:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "1.3 MB" },
  { id: "doc_009", shipmentId: "SH-2965", tenantId: "tenant_cryomed",      type: "customs_declaration",      displayName: "India Import Declaration — ICEGATE",                          status: "pending",                                                                          uploadedBy: "Alex Morgan" },
  { id: "doc_032", shipmentId: "SH-2965", tenantId: "tenant_cryomed",      type: "air_waybill",              displayName: "Air Waybill — Korean Air Cargo AWB-2965",                    status: "complete",  uploadedAt: "2026-03-07T09:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "450 KB" },
  { id: "doc_033", shipmentId: "SH-2965", tenantId: "tenant_cryomed",      type: "export_permit",            displayName: "Korea MFDS Export Permit — Tacrolimus TC-2965",               status: "complete",  uploadedAt: "2026-03-05T11:00:00Z", expiresAt: "2026-09-05T00:00:00Z", uploadedBy: "Alex Morgan",   fileSize: "360 KB" },
  { id: "doc_034", shipmentId: "SH-2965", tenantId: "tenant_cryomed",      type: "temperature_log",          displayName: "Pre-Shipment Temperature Log — Seoul GMP Warehouse",         status: "complete",  uploadedAt: "2026-03-07T08:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "1.9 MB" },
  { id: "doc_035", shipmentId: "SH-2965", tenantId: "tenant_cryomed",      type: "invoice",                  displayName: "Commercial Invoice — CryoMed × ArcticOps #INV-2965",         status: "complete",  uploadedAt: "2026-03-05T12:00:00Z",                                    uploadedBy: "Alex Morgan",   fileSize: "220 KB" },
]
