import type { Notification } from "@/lib/types/notification"

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif_001",
    tenantId: null,
    severity: "critical",
    title: "Temperature excursion — SH-3110",
    message: "Shipment SH-3110 needs attention — temperature in the cryogenic unit has risen to -132°C, approaching the upper safe limit of -140°C. The Cord Blood Stem Cells batch may be at risk.",
    actions: [{ label: "View live data", href: "/shipments/SH-3110" }, { label: "Contact crew" }, { label: "Find cold storage" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-3110",
    read: false,
    createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_002",
    tenantId: "tenant_bioverde",
    severity: "warning",
    title: "Customs delay — SH-1204",
    message: "Shipment SH-1204 is experiencing a customs delay at Nairobi JKIA. Estimated additional wait: 4–6 hours. Current temperature is stable at -18.2°C.",
    actions: [{ label: "View details", href: "/shipments/SH-1204" }, { label: "Notify client" }, { label: "Check alternate clearance" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-1204",
    read: false,
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_003",
    tenantId: null,
    severity: "info",
    title: "SH-2847 checkpoint passed — Dubai Hub",
    message: "Shipment SH-2847 (Insulin Glargine) has cleared Dubai hub checkpoint. Temperature holding at 4.8°C. On track for Frankfurt delivery.",
    actions: [{ label: "View shipment", href: "/shipments/SH-2847" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-2847",
    read: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_004",
    tenantId: null,
    severity: "emergency",
    title: "Critical — Temperature excursion SH-3110",
    message: "URGENT: Shipment SH-3110 (Cord Blood Stem Cells) temperature has risen above -130°C — outside safe range. Immediate action required. Nearest cold storage identified in Sydney.",
    actions: [{ label: "View shipment", href: "/shipments/SH-3110" }, { label: "Alert crew NOW" }, { label: "Locate cold storage" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-3110",
    read: false,
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_005",
    tenantId: "tenant_cryomed",
    severity: "warning",
    title: "Compliance document missing — SH-3110",
    message: "Shipment SH-3110 is missing the Australian Quarantine Import Permit required for Sydney customs clearance. Upload required before landing.",
    actions: [{ label: "View compliance", href: "/shipments/SH-3110" }, { label: "Upload document" }],
    relatedEntityType: "document",
    relatedEntityId: "SH-3110",
    read: false,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_006",
    tenantId: "tenant_bioverde",
    severity: "warning",
    title: "SH-1204 temperature approaching limit",
    message: "Shipment SH-1204 compartment temperature is -16.8°C — approaching the upper safe limit of -15°C while waiting at Nairobi customs. Refrigeration unit is compensating.",
    actions: [{ label: "View temperature", href: "/shipments/SH-1204" }, { label: "Contact crew" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-1204",
    read: false,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_007",
    tenantId: null,
    severity: "warning",
    title: "Weather alert — North Atlantic route",
    message: "Severe weather system developing over North Atlantic may affect SH-3091 and SH-3110 flight paths. Potential 45-minute delay possible.",
    actions: [{ label: "View dashboard", href: "/dashboard" }, { label: "View SH-3091", href: "/shipments/SH-3091" }],
    read: false,
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_008",
    tenantId: null,
    severity: "info",
    title: "System health check complete",
    message: "Daily system health check completed. All temperature simulators operational. GPS stream active for 4/4 in-transit shipments. No connectivity issues detected.",
    actions: [],
    read: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    autoExpires: true,
  },
]
