import type { Notification } from "@/lib/types/notification"

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif_001",
    tenantId: null,
    severity: "critical",
    title: "Temperature excursion — SH-3110",
    message: "Shipment SH-3110 needs attention — temperature in the cryogenic unit has risen to -132°C, approaching the upper safe limit of -140°C. The Cord Blood Stem Cells batch may be at risk.",
    actions: [{ label: "View live data", href: "/shipments/SH-3110" }, { label: "Contact crew" }, { label: "Find cold storage" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-3110",
    read: false,
    createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_002",
    tenantId: "tenant_bioverde",
    severity: "warning",
    title: "Customs delay — SH-1204",
    message: "Shipment SH-1204 is experiencing a customs delay at Nairobi JKIA. Estimated additional wait: 4–6 hours. Current temperature is stable at -18.2°C.",
    actions: [{ label: "View details", href: "/shipments/SH-1204" }, { label: "Notify client" }, { label: "Check alternate clearance" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-1204",
    read: false,
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_003",
    tenantId: null,
    severity: "info",
    title: "Shipment SH-2847 checkpoint passed",
    message: "Shipment SH-2847 (Insulin Glargine) has cleared Dubai hub checkpoint. Temperature holding at 4.8°C. On track for Frankfurt delivery.",
    actions: [{ label: "View shipment", href: "/shipments/SH-2847" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-2847",
    read: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_004",
    tenantId: null,
    severity: "warning",
    title: "Document expiry — Bruno Schmidt",
    message: "Crew member Bruno Schmidt's RID Dangerous Goods Certificate expired on September 30, 2025. Shipment SH-2965 may require document update before border crossing.",
    actions: [{ label: "View crew profile", href: "/transport/crew/crew_007" }, { label: "Update document" }],
    relatedEntityType: "crew",
    relatedEntityId: "crew_007",
    read: false,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_005",
    tenantId: "tenant_cryomed",
    severity: "info",
    title: "SH-2901 delivered successfully",
    message: "Shipment SH-2901 (Plasma Fresh Frozen) has been successfully delivered to CryoMed Tokyo Facility. Temperature log confirmed continuous -22°C throughout transit. All compliance docs submitted.",
    actions: [{ label: "View report", href: "/shipments/SH-2901" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-2901",
    read: true,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_006",
    tenantId: null,
    severity: "warning",
    title: "Low stock alert — Insulin Glargine",
    message: "Stock level for Insulin Glargine (mat_001) has dropped to 12% above minimum threshold. Restock ETA: 3 days.",
    actions: [{ label: "View inventory", href: "/inventory" }, { label: "Initiate restock" }],
    relatedEntityType: "material",
    relatedEntityId: "mat_001",
    read: false,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_007",
    tenantId: "tenant_pharma_alpha",
    severity: "info",
    title: "New procurement request — PharmaAlpha",
    message: "PharmaAlpha Inc. has submitted a new procurement request for 200 units of Adalimumab 40mg/0.8mL. Priority: Express.",
    actions: [{ label: "Review request", href: "/inventory" }, { label: "Approve" }, { label: "Request info" }],
    read: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_008",
    tenantId: null,
    severity: "emergency",
    title: "Critical — Temperature excursion SH-3110",
    message: "URGENT: Shipment SH-3110 (Cord Blood Stem Cells) temperature has risen above -130°C — outside safe range. Immediate action required. Nearest cold storage identified in Sydney.",
    actions: [{ label: "View shipment", href: "/shipments/SH-3110" }, { label: "Alert crew NOW" }, { label: "Locate cold storage" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-3110",
    read: false,
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_009",
    tenantId: null,
    severity: "info",
    title: "New carrier capacity available",
    message: "Polar Aero Med has released 4 additional cold-chain air freight slots for March 10–15. Useful for pending SH-3120 route planning.",
    actions: [{ label: "View carriers", href: "/carriers" }],
    read: true,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_010",
    tenantId: "tenant_cryomed",
    severity: "warning",
    title: "Compliance document missing — SH-3110",
    message: "Shipment SH-3110 is missing the Australian Quarantine Import Permit required for Sydney customs clearance. Upload required before landing.",
    actions: [{ label: "View compliance", href: "/shipments/SH-3110" }, { label: "Upload document" }],
    relatedEntityType: "document",
    relatedEntityId: "SH-3110",
    read: false,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_011",
    tenantId: null,
    severity: "info",
    title: "Route optimization opportunity",
    message: "An alternate routing for SH-2788 (Shanghai → New York) could save $8,400 and reduce CO₂ by 1.2t by rerouting through Rotterdam instead of LA.",
    actions: [{ label: "View route options", href: "/route-planner" }],
    read: true,
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_012",
    tenantId: "tenant_bioverde",
    severity: "info",
    title: "SH-3102 departed Amsterdam",
    message: "Shipment SH-3102 (Human Albumin 20%) has departed Amsterdam Schiphol. Temperature stable at 5.1°C. ETA São Paulo: Mar 8 at 03:00 UTC.",
    actions: [{ label: "Track shipment", href: "/shipments/SH-3102" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-3102",
    read: false,
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_013",
    tenantId: null,
    severity: "warning",
    title: "Weather alert — North Atlantic route",
    message: "Severe weather system developing over North Atlantic may affect SH-3102 flight path. Arctic Express monitoring; potential 45-minute delay possible.",
    actions: [{ label: "View weather overlay", href: "/dashboard" }, { label: "View shipment", href: "/shipments/SH-3102" }],
    read: false,
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_014",
    tenantId: "tenant_pharma_alpha",
    severity: "info",
    title: "SH-3005 delivery confirmed",
    message: "Shipment SH-3005 (Trastuzumab 440mg) delivered to Osaka facility. Recipient signature captured. Final temperature log: 4.2°C avg across journey.",
    actions: [{ label: "View report", href: "/shipments/SH-3005" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-3005",
    read: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_015",
    tenantId: null,
    severity: "info",
    title: "Monthly compliance report ready",
    message: "February 2026 compliance report is ready for review. Overall compliance rate: 94.2%. 3 shipments flagged for documentation follow-up.",
    actions: [{ label: "View report", href: "/compliance" }],
    read: true,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_016",
    tenantId: "tenant_bioverde",
    severity: "warning",
    title: "SH-1204 temperature approaching limit",
    message: "Shipment SH-1204 compartment temperature is -16.8°C — approaching the upper safe limit of -15°C while waiting at Nairobi customs. Refrigeration unit is compensating.",
    actions: [{ label: "View temperature", href: "/shipments/SH-1204" }, { label: "Contact crew" }],
    relatedEntityType: "shipment",
    relatedEntityId: "SH-1204",
    read: false,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_017",
    tenantId: null,
    severity: "info",
    title: "New client onboarded — CryoMed Solutions",
    message: "CryoMed Solutions has completed organization setup and is now active on ArcticOps. Their compliance frameworks: GDP, GMP, WHO PQS, IMDG Code.",
    actions: [{ label: "View tenant", href: "/settings" }],
    read: true,
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_018",
    tenantId: null,
    severity: "info",
    title: "Carrier capacity update",
    message: "FrostLine Rail Cargo has updated their February–March capacity. 12 new slots available on the Warsaw–Moscow rail corridor with -25°C capability.",
    actions: [{ label: "View capacity calendar", href: "/carriers" }],
    read: true,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_019",
    tenantId: "tenant_pharma_alpha",
    severity: "warning",
    title: "Regulatory deadline approaching",
    message: "PharmaAlpha's WHO PQS certification renewal is due in 28 days (April 4, 2026). Documentation must be submitted to WHO by March 28.",
    actions: [{ label: "View regulatory calendar", href: "/compliance" }, { label: "Begin renewal" }],
    read: false,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_020",
    tenantId: null,
    severity: "info",
    title: "System health check complete",
    message: "Daily system health check completed. All temperature simulators operational. GPS stream active for 8/8 in-transit shipments. No connectivity issues detected.",
    actions: [],
    read: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    autoExpires: true,
  },
]
